### ISSUE TITLE
velocity and heading 

### ISSUE THREAD

**Issue by prakash-bisht** [Khrylx/AgentFormer#6]
There is no velocity and heading available in eth and ucy dataset .If it is present in nuscenes data than where i can find it ?
Why we need columns with -1.0 ?
Thanks for the response !

**Comment by Khrylx** [comment]
The heading data is the 16th column in the data:
https://github.com/Khrylx/AgentFormer/blob/main/data/preprocessor.py#L99

Velocities are computed using [finite difference](https://en.wikipedia.org/wiki/Finite_difference_method) of the positions.

Columns with -1.0 mean those data are missing since we are following the KITTI data format.
